const labels={office:'办公软件',learning:'学习软件',life:'生活软件',entertainment:'娱乐软件',games:'游戏软件'};
const icons={office:'▦',learning:'✳',life:'◒',entertainment:'♫',games:'✦'};
const cards=document.querySelector('#cards'),empty=document.querySelector('#empty'),search=document.querySelector('#search');
let catalog=[],category='all',loadError=false;
document.querySelector('#year').textContent=new Date().getFullYear();
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
function safeUrl(value){try{const url=new URL(value,location.href);return ['https:','http:'].includes(url.protocol)?url.href:null}catch{return null}}
function render(){const q=search.value.trim().toLocaleLowerCase();const list=catalog.filter(item=>(category==='all'||item.category===category)&&(!q||[item.name,item.description,item.developer,(item.tags||[]).join(' ')].join(' ').toLocaleLowerCase().includes(q)));
 cards.replaceChildren();document.querySelector('#result-count').textContent=loadError?'目录暂时无法读取':`共 ${list.length} 款软件${category==='all'?'':` · ${labels[category]}`}`;
 for(const item of list){const card=el('article','card');const head=el('div','card-head');head.append(el('div','card-icon',icons[item.category]||'✳'),el('span','card-tag',labels[item.category]||'软件'));card.append(head,el('h3','',item.name),el('p','',item.description));const bottom=el('div','card-bottom');bottom.append(el('span','',`${item.systems.join(' / ')} · v${item.version}`));const btn=el('button','', '查看详情 ↗');btn.type='button';btn.addEventListener('click',()=>showDetails(item));bottom.append(btn);card.append(bottom);cards.append(card)}
 empty.hidden=list.length!==0;const noMatch=catalog.length>0&&(q||category!=='all');document.querySelector('#empty-title').textContent=loadError?'目录暂时不可用':noMatch?'没有找到匹配的软件':'好软件，正在路上。';document.querySelector('#empty-text').textContent=loadError?'请稍后刷新页面重试。':noMatch?'试试其他关键词或分类。':'目录正在筹备中。第一批软件发布后，就能在这里查看介绍与下载地址。';document.querySelector('#clear-search').hidden=!noMatch;
}
function showDetails(item){const dialog=document.querySelector('#details'),content=document.querySelector('#details-content');content.replaceChildren(el('span','card-tag',labels[item.category]),el('h2','',item.name),el('p','',item.description));const dl=el('dl');for(const [name,value] of [['开发者',item.developer],['版本',item.version],['适用系统',item.systems.join(' / ')],['许可类型',item.license],['文件大小',item.size||'请查看下载页'],['SHA-256',item.sha256||'请查看官方页面'],['来源',item.source]]){dl.append(el('dt','',name),el('dd','',value))}content.append(dl);const url=safeUrl(item.downloadUrl);if(url){const a=el('a','download-link',item.source==='本站托管'?'下载软件 ↗':'前往官方下载 ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';content.append(a)}dialog.showModal()}
document.querySelector('.close-dialog').addEventListener('click',()=>document.querySelector('#details').close());document.querySelector('#details').addEventListener('click',e=>{if(e.target.tagName==='DIALOG')e.target.close()});
for(const button of document.querySelectorAll('.filter'))button.addEventListener('click',()=>{category=button.dataset.category;document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button?'true':'false')});render()});
for(const link of document.querySelectorAll('[data-jump]'))link.addEventListener('click',()=>document.querySelector(`.filter[data-category="${link.dataset.jump}"]`).click());
search.addEventListener('input',render);document.querySelector('#clear-search').addEventListener('click',()=>{search.value='';document.querySelector('.filter[data-category="all"]').click();search.focus()});
fetch('catalog.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('catalog HTTP '+r.status);return r.json()}).then(data=>{if(!Array.isArray(data))throw new Error('invalid catalog');catalog=data.filter(item=>item&&item.name&&labels[item.category]&&Array.isArray(item.systems)&&item.version&&item.description);render()}).catch(error=>{console.error('读取软件目录失败',error);loadError=true;render()});
